export const API_PREFIX = '/api/v1';

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PDF_PROCESSING_ERROR: 'PDF_PROCESSING_ERROR',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const MAX_PDF_SIZE_BYTES = 100 * 1024 * 1024; // 100 MB
export const ALLOWED_PDF_MIME_TYPES = ['application/pdf'];
